at:
  lucny:
    p2p-backup:
      user: user3
      config-dir: ../${at.lucny.p2p-backup.user}_config
      keystore: file:../keys/${at.lucny.p2p-backup.user}.pfx
      certificate: file:../keys/${at.lucny.p2p-backup.user}.pem
      network:
        port: 9003
      init:
        users:
          - user: user1
            address: localhost
            port: 9001
            certificate-path: ../keys/user1.pem
            allow-backup-from-user: true
            allow-backup-to-user: true
          - user: user2
            address: localhost
            port: 9002
            certificate-path: ../keys/user2.pem
            allow-backup-from-user: true
            allow-backup-to-user: true
          - user: user4
            address: localhost
            port: 9004
            certificate-path: ../keys/user4.pem
            allow-backup-from-user: true
            allow-backup-to-user: true
        root-directories:
          - name: userdata
            path: ${at.lucny.p2p-backup.config-dir}/data
        cloud-provider:
          #  - id: at.lucny.p2pbackup.cloud.nextcloud.service.NextcloudStorageServiceImpl
          #    properties:
          #      service-url: https://nextcloud.lucny.at
          #      #username:
          #      #password: 
          - id: at.lucny.p2pbackup.cloud.filesystem.service.FilesystemStorageServiceImpl
            properties:
              directory: ${at.lucny.p2p-backup.config-dir}/cloud

logging:
  level:
    ROOT: INFO
